variables:
  JEKYLL_ENV: production
  PATH: /usr/global/tools/ruby/toss_3_x86_64_ib/bin:/usr/bin:/bin
  GEM_HOME: /usr/global/tools/ruby/toss_3_x86_64_ib/lib/ruby/gems
  SITE_HOME: /usr/global/web-pages/www-lc/docs

before_script:
  - echo $PATH
  - echo $GEM_HOME
# NOTE: Jeff Long (jwlong) owns the /collab/usr/global/tools/ruby install and only he should install things
#   - bundle install

test:
  stage: test
  tags:
  - shell
  - toss_3_x86_64
  script:
  - test -d $SITE_HOME
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  # except:
  # - main

deploy:
  stage: deploy
  tags:
  - shell
  - toss_3_x86_64
  script:
  - bundle exec jekyll build -d public
  - rsync -r --delete public/ $SITE_HOME/
  after_script:
  - chmod -R g+rwX,o+rX $SITE_HOME/ 2>/dev/null
  artifacts:
    paths:
    - public
  only:
  - main
